### ISSUE TITLE
Readonly user for Grafana

### ISSUE THREAD

**Issue by prasenforu** [mrsiano/grafana-ocp#11]
First of all I want to say thank you for nice blog https://blog.openshift.com/prometheus-alerts-on-openshift

I just followed above blog and deployed entire things successfully.

After that I created new "demouser" user in openshift and given permission (policy) as read only for grafana project for listing pod,svc,route. 
Through console & CLI user able to do all activity as per policy and user can go to dashboard also.

But problem is that policy (read) is applied in openshift not in Grafana as a result user able to modify the dash board and others.

What I am looking user should NOT do any modification in grafana dashboard or anything on GUI.
So user should also be as read only similar like openshift.

**Comment by mrsiano** [comment]
please try 
https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_cluster_monitoring_operator
it should have read permissions only

**Comment by rodrigobersa** [comment]
Facing the same issue where accounts with Namespace View Role can edit everything inside Grafana. Anything like Cluster Monitoring Operator for OCP v3.9?

**Comment by mrsiano** [comment]
@rodrigobersa unfortunately no.
custom setup is need for 3.11

tweak you ansible playbook for that like the prometheus namespace and serviceaccount

**Comment by fuxes** [comment]
@mrsiano could you please give more detailed information on how-to?
