### ISSUE TITLE
Local rendering not working

### ISSUE THREAD

**Issue by Svonn** [mrsiano/grafana-ocp#13]
Setting 

[external_image_storage]
provider = local

Resulting in Phantomjs exiting with exitcode 127

t=2018-07-05T10:50:10+0000 lvl=info msg=Rendering logger=rendering path="d-solo/000000006/monitoring?panelId=11"
t=2018-07-05T10:50:10+0000 lvl=eror msg="Phantomjs exited with non zero exit code" logger=rendering error="exit status 127"
t=2018-07-05T10:50:10+0000 lvl=eror msg="Failed to upload alert panel image." logger=alerting.notifier error="exit status 127"

According to this:
https://github.com/ariya/phantomjs/issues/13597

The build might be missing libfreetype6 and libfontconfig

**Comment by mrsiano** [comment]
please try
https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_grafana
or 
https://github.com/openshift/cluster-monitoring-operator
