### ISSUE TITLE
Warning: Couldn't read data from file "./node-exporter-full-dashboard.json",

### ISSUE THREAD

**Issue by pennpeng** [mrsiano/grafana-ocp#14]
Warning: Couldn't read data from file "./node-exporter-full-dashboard.json",

**Comment by sleter** [comment]
Bump

**Comment by mrsiano** [comment]
hmmm.
can you try to use 
https://github.com/openshift/cluster-monitoring-operator
or 
https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_grafana

**Comment by sleter** [comment]
Actually I tried to run script a few times and it worked. I couldn't reproduce the issue later
