### ISSUE TITLE
Datasource Promethues with Oauth

### ISSUE THREAD

**Issue by alekonko** [mrsiano/grafana-ocp#15]
Hi, 
 now we use a custom docker image with grafana (now 5.2.1 version)  rhel 7 based.

For access to a Openshift Prometheus (rel 3.9) we use a simple ambassador container written in go and inserted into grafana pod.
it expose a 9090 port and forward autenticate call to real a Prometheus.

Have you plan to create a separate ds_plugin for prometheus with OAuth ?

**Comment by mrsiano** [comment]
hi thanks for your feedback 
please see
https://github.com/openshift/cluster-monitoring-operator
