### ISSUE TITLE
Deploying grafana manually fails as the container image can not be found

### ISSUE THREAD

**Issue by DuncanDoyle** [mrsiano/grafana-ocp#17]
grafana-ocp.yaml fails to deploy the container in OpenShift, as it fails on pulling the image from DockerHub.

Seems that the template is configured to pull this image "mrsiano/openshift-grafana:latest", but the "latest" tag seems to be missing in DockerHub: https://hub.docker.com/r/mrsiano/openshift-grafana/tags/

Changing the version to 5.2.0 fixed the problem.

**Comment by mrsiano** [comment]
hmm, please try to use the 5.2.0 tag
on the other hand, I strongly suggest you to use in https://github.com/openshift/cluster-monitoring-operator

https://github.com/openshift/openshift-ansible/tree/master/roles/openshift_cluster_monitoring_operator

it will deploy for you the whole monitoring stack
