### ISSUE TITLE
the dashboard json is outdated, sync it with origin.

### ISSUE THREAD

**Issue by pennpeng** [mrsiano/grafana-ocp#5]
i use ansible-playbook deploy the prometheus from https://github.com/openshift/openshift-ansible/tree/release-3.7/roles/openshift_prometheus , and  i use yours dashboard template, there just Display partial data???

**Comment by mrsiano** [comment]
what do you mean, what data is missing ?

**Comment by pennpeng** [comment]
Hi, the "Network I/O pressure","Cluster CPU usage" "Cluster filesystem usage","Cluster CPU Usage","Pods CPU usage" "Containers Cores Usage" and  so on, there is  no data.

**Comment by mrsiano** [comment]
and other graphs are ok ?! if not it may be because wrong datasource, otherwise something might be bad in the query itself.
also, inside the query editor try to change the irate time from 2m to something bigger like 10m.

**Comment by pennpeng** [comment]
Hi,
1,your default irate time is 30s,when i changed to 2m,it is display the graphs.
2,my docker Storage Driver is overlay2, so the filesystem usage no graphs
3,in the "promethes"and "API server",the "drop_common_labels"functions was removed in promethes 2.0,the release is "https://github.com/prometheus/prometheus/releases/tag/v2.0.0"

**Comment by mrsiano** [comment]
@pennpeng cool, we have a newer json for dashboarding so here it might be the outdated one.
track that PR as well
#https://github.com/openshift/release/pull/455

**Comment by mrsiano** [comment]
@pennpeng try to use the last commit

**Comment by pennpeng** [comment]
Hi，the last commit  is ok！

**Comment by mrsiano** [comment]
10x!
