### ISSUE TITLE
Grafana.log is empty

### ISSUE THREAD

**Issue by olaf-meyer** [mrsiano/grafana-ocp#6]
If I create a pod/container based on the docker image "mrsiano/grafana-ocp" the log files grafana.log in the folder "/root/go/src/github.com/grafana/data/log" is empty. Do I look in the correct spot or is it possible to increase the log granularity?

**Comment by mrsiano** [comment]
you should change the log level here:
https://github.com/mrsiano/grafana-ocp/blob/56d980e75ec9818155a4b1b35bebb0c3a85b14f4/grafana-ocp-oauth.yaml#L502

**Comment by olaf-meyer** [comment]
Thank you a lot. That was exactly what I was looking for.
