### ISSUE TITLE
Request to add explicit license

### ISSUE THREAD

**Issue by davidaah** [mrsiano/grafana-ocp#7]
hi @mrsiano this seems like a really great tool and I would be interested in trying it out. is it possible for you to attach a license (eg. Apache 2 or MIT) to this repo/project?

**Comment by mrsiano** [comment]
Can you try this meanwhile https://github.com/openshift/origin/tree/master/examples/grafana

**Comment by davidaah** [comment]
sure will check it out, thank you!
