### ISSUE TITLE
Provisioning

### ISSUE THREAD

**Issue by Br0mZ** [mrsiano/grafana-ocp#8]
It seems that provisioning is not working in this Grafana version.
I tried the latest Grafana version; which shows in the log: lvl=info msg="Path Provisioning" logger=settings path=/root/go/src/github.com/grafana/grafana/provisioning

This ini setting is not recognised in the 4.7pre1 version you built.

Can you update the forked grafana repo of help me in modifying the newest version to use OAuth?

**Comment by mrsiano** [comment]
can you share the error you faced and how you faced it? 
you just run the ./setup-grafana.sh ?

**Comment by Br0mZ** [comment]
I've made yaml files for the deployment, route, service, etc.. and used your forked grafana version.
Everything works as expected.
However, I want to use the new provisioning options, available from Grafana 5.
I hoped they were already implemented in the version you forked (4.7pre1), but according to the grafana.log, the provisioning path is not recognized at startup.
I tried the Grafana version on dockerhub, which is the latest version, combined with my ini file, and in the grafana.log is recognizes the provisioning path.

Since I'm using Openshift, I'm happy with your modified version, but would like to use the newest features.

I tried merging the upstream grafana version into your OAuth branch.
After that I adjusted the Dockerfile to use the local merged grafana version.
I can run the Dockerfile but it fails in the go build commands:

```
# github.com/grafana/grafana/vendor/github.com/grafana/grafana_plugin_model/go/datasource
vendor/github.com/grafana/grafana_plugin_model/go/datasource/service.go:20: cannot use GRPCServer literal (type *GRPCServer) as type DatasourcePluginServer in argument to RegisterDatasourcePluginServer:
  *GRPCServer does not implement DatasourcePluginServer (wrong type for Query method)
    have Query("context".Context, *DatasourceRequest) (*DatasourceResponse, error)
    want Query("github.com/grafana/grafana/vendor/golang.org/x/net/context".Context, *DatasourceRequest) (*DatasourceResponse, error)
github.com/grafana/grafana/vendor/golang.org/x/sync/errgroup
github.com/grafana/grafana/vendor/golang.org/x/oauth2/jwt
github.com/grafana/grafana/pkg/social
github.com/grafana/grafana/pkg/tsdb/testdata
github.com/grafana/grafana/vendor/github.com/aws/aws-sdk-go/aws/request
# github.com/grafana/grafana/pkg/social
pkg/social/social.go:114: cannot use SocialGithub literal (type *SocialGithub) as type SocialConnector in assignment:
  *SocialGithub does not implement SocialConnector (wrong type for Client method)
    have Client("github.com/grafana/grafana/vendor/golang.org/x/net/context".Context, *oauth2.Token) *http.Client
    want Client("context".Context, *oauth2.Token) *http.Client
pkg/social/social.go:128: cannot use SocialGoogle literal (type *SocialGoogle) as type SocialConnector in assignment:
  *SocialGoogle does not implement SocialConnector (wrong type for Client method)
    have Client("github.com/grafana/grafana/vendor/golang.org/x/net/context".Context, *oauth2.Token) *http.Client
    want Client("context".Context, *oauth2.Token) *http.Client
pkg/social/social.go:143: cannot use SocialGenericOAuth literal (type *SocialGenericOAuth) as type SocialConnector in assignment:
  *SocialGenericOAuth does not implement SocialConnector (wrong type for Client method)
    have Client("github.com/grafana/grafana/vendor/golang.org/x/net/context".Context, *oauth2.Token) *http.Client
    want Client("context".Context, *oauth2.Token) *http.Client
pkg/social/social.go:166: cannot use SocialGrafanaCom literal (type *SocialGrafanaCom) as type SocialConnector in assignment:
  *SocialGrafanaCom does not implement SocialConnector (wrong type for Client method)
    have Client("github.com/grafana/grafana/vendor/golang.org/x/net/context".Context, *oauth2.Token) *http.Client
    want Client("context".Context, *oauth2.Token) *http.Client
github.com/grafana/grafana/vendor/github.com/prometheus/client_golang/prometheus/promhttp
```

**Comment by skynardo** [comment]
I am having a similar issue using the 5.2.0 image.
Ran  ./setup-grafana.sh -n prometheus-ocp openshift-metrics true
Added persistent storage for grafana-data → /root/go/src/github.com/grafana/grafana/data 
Unable to successfully add prometheus-ocp datasource, clicking Test shows an error. The only errors I see in the grafana logs are:

t=2018-06-07T19:46:12+0000 lvl=eror msg="can't read datasource provisioning files from directory" logger=provisioning.datasources path=/root/go/src/github.com/grafana/grafana/datasources
 t=2018-06-07T19:46:12+0000 lvl=eror msg="can't read dashboard provisioning files from directory" logger=provisioning.dashboard path=/root/go/src/github.com/grafana/grafana/dashboards

**Comment by skynardo** [comment]
I apologize if I muddied the waters, my issue was due to missing the = on the openshift-metrics=true. I also noticed that this version creates the datasource for you along with Token/Secrets. Thanks.
