### ISSUE TITLE
Cannot connect prometheus to grafana in openshift

### ISSUE THREAD

**Issue by martin123218** [mrsiano/grafana-ocp#9]
Hello,

Before anything thanks for making this grafana build for openshift.
My problem is that I can't connect the newest grafana image to openshift prometheus for the moment.

Prom-proxy container in prometheus keeps spaming the following logs

2018/05/31 13:14:21 oauthproxy.go:657: 10.129.0.1:51024 Cookie "_oauth_proxy" not present
2018/05/31 13:14:21 provider.go:345: authorizer reason: User "system:anonymous" cannot get namespaces in project "openshift-metrics"

In the previous version with image ocp-mrsiano I connect it via token, but now that token is missing.
I tried using tls-client auth with prometheus-tls key and cert but I didn't solve the problem.

I tried clear installation with the following ansible variables. But The prometheus couldn't connect again.

# Grafana
openshift_grafana_pvc_pv_selector=None
openshift_grafana_storage_type=pvc
openshift_grafana_sc_name=glusterfs-storage	
openshift_grafana_pvc_size=2Gi
openshift_grafana_node_selector={'region':'infra'}
openshift_grafana_image=mrsiano/openshift-grafana:5.2.0
openshift_grafana_proxy_image=openshift/oauth-proxy:v1.0.0

I've tried many combinations with secrets in openshift-metrics namespaces and username and password and it won't work.

Any help will be appreciated.

Thanks,

Best Regards,

Martin

![screenshot from 2018-05-31 16-42-21](https://user-images.githubusercontent.com/16573583/40785611-a1d38178-64f1-11e8-9d18-fdc4d02d3688.png)

**Comment by martin123218** [comment]
Hello Again,

I see the difference between the two versions old version 4.7 has token field where openshift sa token has been pasted on the new version 5.2 as you can see this field is missing and probably this cause prometheus not to see grafana. My question is how to connect grafana and prometheus here?

Thanks and Regards,

Martin

**Comment by mrsiano** [comment]
right, that beacuse the following PR https://github.com/grafana/grafana/pull/11643#issuecomment-393756081

we working on to use generic headers,
can you try to use the setup script instead of run it manually ?!

the UI still not run this changes and currently we have to use grafana api in order to carry the new payload structure 
https://github.com/mrsiano/openshift-grafana/blob/2768d8f0147a7a5209c1d193e542dea5947752c0/setup-grafana.sh#L97

the simplest will be run the setup-script

**Comment by martin123218** [comment]
Hello,
Thanks. That way worked.

I am closing the ticket. 

Best Regards,

Martin

**Comment by mrsiano** [comment]
Great Thanks Martin
